# Generated by Django 2.2 on 2021-08-30 08:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_oppia_log'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('courses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=50),
        ),
    ]
