version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:2.7.15-jessie-node-browsers
        environment:
          DEBUG: True
          DATABASE_URL: mysql://localhost/circle_test
          DJANGO_SETTINGS_MODULE: "config.ci_settings"
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - restore_cache:
          key: pythonDeps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements/base.txt" }}--{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv .venv
            source .venv/bin/activate
            yes w | pip install -r requirements.txt
            yes w | pip install -r requirements/test.txt
            pip install dj-database-url
      - save_cache:
          key: pythonDeps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements/base.txt" }}--{{ checksum "requirements/test.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            source .venv/bin/activate
            python manage.py collectstatic --noinput
      - run:
          command: |
            source .venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
